class StrArray:
    def __init__(self): ...
    def __setitem__(self, _i: int, _val: str) -> None: ...
    def __getitem__(self, _i: int) -> str: ...
    def __len__(self) -> int: ...
    def __list__(self) -> list: ...
    def __iter__(self) -> StrArrayIterator: ...
    def append(self, _val: str) -> None: ...
    def index(self, _val: str) -> int: ...
    def pop(self, _i: int) -> None: ...
class StrArrayIterator:
    def __init__(self, arr: StrArrayIterator) -> None: ...
    def __next__(self) -> str: ...