class StrArray:
    def __init__(self): ...
    def __setitem__(self, _i: int, _val: bytes) -> None: ...
    def __getitem__(self, _i: int) -> bytes: ...
    def append(self, _val: bytes) -> None: ...
    def __len__(self) -> int: ...